"""create chat table

Revision ID: 69e21d3cb9cf
Revises: c5097774038e
Create Date: 2018-11-14 18:52:02.084386

"""
from alembic import op
import sqlalchemy as sa
#from sqlalchemy import false
from sqlalchemy.sql import func, text


# revision identifiers, used by Alembic.
revision = '69e21d3cb9cf'
down_revision = 'c5097774038e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=64), default='', nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=func.now(), nullable=False),
    sa.Column('is_live', sa.Integer(), nullable=False, server_default=text("0") ),
    #no boolean in sqlite. 
    #sa.Column('is_live', sa.Boolean(create_constraint=False), nullable=False, default=False, server_default="0"),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_created_at'), 'chat', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_title'), 'chat', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_title'), table_name='chat')
    op.drop_index(op.f('ix_chat_created_at'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
