"""subscription

Revision ID: ce8832672da6
Revises: 69e21d3cb9cf
Create Date: 2018-11-19 11:25:57.636111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8832672da6'
down_revision = '69e21d3cb9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('subscriber_user_id', sa.String(length=32), nullable=True),
    sa.Column('subscribee_user_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['subscribee_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscriber_user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    # ### end Alembic commands ###
